
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.css';
import './globals.css'
import Script from 'next/script';
import Header from './common/Header';
import Footer from './common/Footer';
import { usePathname } from 'next/navigation';
import MainContext from '@/Context/MainContext';





const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  


  return (
    <html lang="en">
      <body className={inter.className}>
        
        
         
      <MainContext>
          <Header/>
        {children}
          <Footer/>
      </MainContext>

        </body>
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"/>
    </html>
  )
}
